/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhj_crazy_ndklib_NdkUserInterface */

#ifndef _Included_com_zhj_crazy_ndklib_NdkUserInterface
#define _Included_com_zhj_crazy_ndklib_NdkUserInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhj_crazy_ndklib_NdkUserInterface
 * Method:    getNdkString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zhj_crazy_ndklib_NdkUserInterface_getNdkString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
